### ISSUE TITLE
NPE when shutting down helper-redis

### ISSUE THREAD

**Issue by Baricaade** [lucko/helper#100]
Hi,

Getting an NPE from helper-redis when shutting down the server, still happens when nothing is using helper-redis too.

`at me.lucko.helper.redis.plugin.HelperRedis$1.run(HelperRedis.java:90)
at me.lucko.helper.utils.Delegates$RunnableToSupplier.get(Delegates.java:127)
at me.lucko.helper.promise.HelperPromise$SupplyRunnable.run(HelperPromise.java:677)
at me.lucko.helper.scheduler.HelperExecutors$SchedulerWrappedRunnable.run(HelperExecutors.java:95)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NullPointerException
at java.base/java.lang.String.<init>(String.java:561)
at me.lucko.helper.redis.plugin.HelperRedis$PubSubListener.onUnsubscribe(HelperRedis.java:194)
at redis.clients.jedis.BinaryJedisPubSub.process(BinaryJedisPubSub.java:100)
at redis.clients.jedis.BinaryJedisPubSub.proceedWithPatterns(BinaryJedisPubSub.java:75)
at redis.clients.jedis.BinaryJedis.psubscribe(BinaryJedis.java:3349)
at me.lucko.helper.redis.plugin.HelperRedis$1.run(HelperRedis.java:87)`

**Comment by lucko** [comment]
If I had to guess I'd say you are subscribing to a null channel somewhere by mistake.
