### ISSUE TITLE
No Registration

### ISSUE THREAD

**Issue by GamerPlands** [lucko/helper#144]
[21:42:48 ERROR]: Error occurred while enabling Minetopia-Beta v1.0.0 (Is it up to date?)
java.lang.IllegalStateException: No registration present for service 'me.lucko.helper.profiles.ProfileRepository'
        at me.lucko.helper.Services.lambda$load$0(Services.java:57) ~[?:?]
        at java.util.Optional.orElseThrow(Unknown Source) ~[?:1.8.0_351]
        at me.lucko.helper.Services.load(Services.java:57) ~[?:?]
        at dev.maiky.minetopia.Minetopia.enable(Minetopia.java:165) ~[?:?]
        at me.lucko.helper.plugin.ExtendedJavaPlugin.onEnable(ExtendedJavaPlugin.java:100) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[server.jar:git-Bukkit-f4830a1]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:329) [server.jar:git-Bukkit-f4830a1]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [server.jar:git-Bukkit-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:367) [server.jar:git-Bukkit-f4830a1]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:328) [server.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:412) [server.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:373) [server.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:328) [server.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:248) [server.jar:git-Bukkit-f4830a1]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:522) [server.jar:git-Bukkit-f4830a1]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_351]

**Comment by ThePotatoDev** [comment]
You have to provide the "helper-profiles" plugin on your physical server instance to access the provided registered ProfileRepository service in any other project. Is the plugin currently on your server?
