### ISSUE TITLE
Hello, I tried support via discord and didn't get a response, I'm trying to create a hologram using the helper.

### ISSUE THREAD

**Issue by walmorhenrique** [lucko/helper#151]
`                    Position position = Position.of(location);

                    // Create a list of hologram lines using the builder
                    List<HologramLine> lines = HologramLine.builder()
                            .line("Hello, ")
                            .line("test")
                            .line("!")
                            .build();

                    //I tried this:
                    //PacketIndividualHologramFactory factory = Services.load(PacketIndividualHologramFactory.class);
                    //this:
                    IndividualHologramFactory factory = Services.load(IndividualHologramFactory.class);
                    IndividualHologram hd = factory.newHologram(position, lines);
                    hd.spawn();`

error: java.lang.IllegalStateException: No registration present for service 'me.lucko.helper.hologram.individual.IndividualHologramFactory'
        at me.lucko.helper.Services.lambda$load$0(Services.java:57) ~[helper.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at me.lucko.helper.Services.load(Services.java:57) ~[helper.jar:?]
        at net.voxymc.voxylobby.systems.server.npc.LoadNpc.loadNpcS(LoadNpc.java:106) ~[VoxyLobby-1.0-SNAPSHOT-all.jar:?]
        at net.voxymc.voxylobby.systems.server.ServerMain.load(ServerMain.java:32) ~[VoxyLobby-1.0-SNAPSHOT-all.jar:?]
        at net.voxymc.voxylobby.Main.onEnable(Main.java:57) ~[VoxyLobby-1.0-SNAPSHOT-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1019) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:549) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:321) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at java.lang.Thread.run(Thread.java:833) ~[?:?] 

other test:  java.lang.IllegalStateException: No registration present for service 'me.lucko.helper.hologram.individual.IndividualHologramFactory'
        at me.lucko.helper.Services.lambda$load$0(Services.java:57) ~[helper.jar:?]
        at java.util.Optional.orElseThrow(Optional.java:403) ~[?:?]
        at me.lucko.helper.Services.load(Services.java:57) ~[helper.jar:?]
        at me.lucko.helper.hologram.individual.IndividualHologram.create(IndividualHologram.java:52) ~[helper.jar:?]
        at net.voxymc.voxylobby.systems.server.npc.LoadNpc.loadNpcS(LoadNpc.java:106) ~[VoxyLobby-1.0-SNAPSHOT-all.jar:?]
        at net.voxymc.voxylobby.systems.server.ServerMain.load(ServerMain.java:32) ~[VoxyLobby-1.0-SNAPSHOT-all.jar:?]
        at net.voxymc.voxylobby.Main.onEnable(Main.java:57) ~[VoxyLobby-1.0-SNAPSHOT-all.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:541) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:560) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:474) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.reload(CraftServer.java:1019) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.Bukkit.reload(Bukkit.java:909) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:54) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[purpur-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchCommand(CraftServer.java:906) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at org.bukkit.craftbukkit.v1_18_R2.CraftServer.dispatchServerCommand(CraftServer.java:869) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.handleConsoleInputs(DedicatedServer.java:549) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:523) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1483) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1247) ~[purpur-1.18.2.jar:git-Purpur-1632]
        at net.minecraft.server.MinecraftServer.lambda$sp

If any humble soul can help me, I'm working with the paper version 1.18.2

**Comment by joestr** [comment]
Do you have the ProtocolLib plugin installed on your server?
