### ISSUE TITLE
Error with PaginatedGui

### ISSUE THREAD

**Issue by vikicraft** [lucko/helper#32]
Got this PaginatedGui :  
```java
public class TitlesGui extends PaginatedGui {

    private static final MenuScheme DECORATION_SCHEME = new MenuScheme()
            .mask("100000001")
            .mask("100000001")
            .mask("100000001");

    private static final MenuScheme TITLES_SCHEME = new MenuScheme()
            .mask("011111110")
            .mask("011111110")
            .mask("000000000");

    private static final MenuScheme RESET_BUTTON_SCHEME = new MenuScheme()
            .maskEmpty(2)
            .mask("000010000");

    public TitlesGui(Player p) {
        super(paginatedGui -> new ArrayList<>(), p,
                PaginatedGuiBuilder.create().lines(3).title("Mes titres")
                        .itemSlots(TITLES_SCHEME.getMaskedIndexesImmutable())
                        .nextPageSlot(new MenuScheme()
                                .maskEmpty(2)
                                .mask("001000000")
                                .getMaskedIndexes().get(0))
                        .previousPageSlot(new MenuScheme()
                                .maskEmpty(2)
                                .mask("000000100")
                                .getMaskedIndexes().get(0))
                        .nextPageItem(pageInfo -> ItemStackBuilder.of(Material.ARROW)
                                .name("&6Page suivante")
                                .build())
                        .previousPageItem(pageInfo -> ItemStackBuilder.of(Material.ARROW)
                                .name("&6Page précédente")
                                .build())
        );
        updateContent(getTitles());
    }

    public List<Item> getTitles() {
        List<Item> content = new ArrayList<>();
        for (Title title : VikicraftTitles.getTitles()) {
            if (!VikicraftTitles.hasUnlocked(getPlayer(), title)) continue;

            ItemStackBuilder itemStack = title.buildItem();

            if (title.equals(VikicraftTitles.getTitle(getPlayer()))) {
                itemStack.enchant(Enchantment.LUCK);
                itemStack.flag(ItemFlag.HIDE_ENCHANTS);
            }

            Item item = Item.builder(itemStack.build()).bind(ClickType.LEFT, () -> {
                VikicraftTitles.setTitle(getPlayer(), title);
                Players.msg(getPlayer(), "&aTon titre a été changé en "+title.getTag());
                updateContent(getTitles());
                redraw();
            }).build();

            content.add(item);
        }

        return content;
    }

    @Override
    public void redraw() {
        super.redraw();

        if (isFirstDraw()) {
            // decoration
            DECORATION_SCHEME.newPopulator(this)
                    .acceptIfSpace(ItemStackBuilder.of(Material.STAINED_GLASS_PANE).buildItem().build());

            // reset button
            Item resetButton = Item.builder(
                    ItemStackBuilder.of(Material.BARRIER)
                            .name("&cRetirer mon titre")
                            .build()
            ).bind(ClickType.LEFT, () -> {
                VikicraftTitles.setTitle(getPlayer(), null);
                Players.msg(getPlayer(), "&aTon titre a été retiré.");
                updateContent(getTitles());
                redraw();
            }).build();

            RESET_BUTTON_SCHEME.newPopulator(this)
                    .acceptIfSpace(resetButton);
        }
    }

}
````

It gives me this error, tried to fix it but it seems it's helper's side :

```
[13:12:17 WARN]: java.lang.IllegalArgumentException: Invalid slot id: 27
[13:12:17 WARN]:        at me.lucko.helper.menu.Gui.getSlot(Gui.java:167)
[13:12:17 WARN]:        at me.lucko.helper.menu.Gui.setItem(Gui.java:174)
[13:12:17 WARN]:        at me.lucko.helper.menu.scheme.MenuScheme.lambda$apply$0(MenuScheme.java:142)
[13:12:17 WARN]:        at java.util.Optional.ifPresent(Optional.java:159)
[13:12:17 WARN]:        at me.lucko.helper.menu.scheme.MenuScheme.apply(MenuScheme.java:142)
[13:12:17 WARN]:        at me.lucko.helper.menu.paginated.PaginatedGui.redraw(PaginatedGui.java:80)
[13:12:17 WARN]:        at net.vikicraft.titles.gui.TitlesGui.redraw(TitlesGui.java:84)
[13:12:17 WARN]:        at me.lucko.helper.menu.Gui.open(Gui.java:256)
[13:12:17 WARN]:        at net.vikicraft.titles.VikicraftTitles.lambda$enable$0(VikicraftTitles.java:67)
[13:12:17 WARN]:        at me.lucko.helper.command.functional.FunctionalCommand.call(FunctionalCommand.java:58)
[13:12:17 WARN]:        at me.lucko.helper.command.AbstractCommand.onCommand(AbstractCommand.java:57)
[13:12:17 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[13:12:17 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152)
[13:12:17 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:685)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1492)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1297)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:5)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:14)
[13:12:17 WARN]:        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[13:12:17 WARN]:        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:850)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:423)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774)
[13:12:17 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666)
[13:12:17 WARN]:        at java.lang.Thread.run(Thread.java:748)
```

**Comment by lucko** [comment]
Sorry for the super late reply - this probably isn't even useful now! but you need to override `.scheme(...)` in the PaginatedGui builder.
