### ISSUE TITLE
"Events" and "Commands" are no longer valid for Helper-JS

### ISSUE THREAD

**Issue by JamieSinn** [lucko/helper#8]
`javax.script.ScriptException: ReferenceError: "Commands" is not defined in nashorn:mozilla_compat.js at line number 67
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.api.scripting.NashornScriptEngine.throwAsScriptException(NashornScriptEngine.java:470)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:454)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:406)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:402)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
2018-02-15 14:28:17 [WARN] 	at me.lucko.scriptcontroller.internal.ScriptImpl.run(ScriptImpl.java:162)
2018-02-15 14:28:17 [WARN] 	at me.lucko.scriptcontroller.internal.ScriptLoaderImpl.lambda$reload$1(ScriptLoaderImpl.java:294)
2018-02-15 14:28:17 [WARN] 	at me.lucko.helper.Scheduler$SchedulerWrappedRunnable.run(Scheduler.java:638)
2018-02-15 14:28:17 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:71)
2018-02-15 14:28:17 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:353)
2018-02-15 14:28:17 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:739)
2018-02-15 14:28:17 [WARN] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
2018-02-15 14:28:17 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
2018-02-15 14:28:17 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
2018-02-15 14:28:17 [WARN] 	at java.lang.Thread.run(Unknown Source)
2018-02-15 14:28:17 [WARN] Caused by: nashorn:mozilla_compat.js:67 ReferenceError: "Commands" is not defined
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:319)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ECMAErrors.referenceError(ECMAErrors.java:291)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.objects.Global.__noSuchProperty__(Global.java:1441)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.scripts.Script$Recompilation$9$1362A$\=nashorn\!mozilla_compat.value-1#__noSuchProperty__(nashorn:mozilla_compat.js:67)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.scripts.Script$17$gui.:program(plugins/helper-js/scripts/bin/lobby/gui.js:39)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.Context.evaluateSource(Context.java:1222)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.Context.load(Context.java:839)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.objects.Global.load(Global.java:1545)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.scripts.Script$16$\^eval\_.:program(<eval>:1)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ScriptFunctionData.invoke(ScriptFunctionData.java:637)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ScriptFunction.invoke(ScriptFunction.java:494)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.internal.runtime.ScriptRuntime.apply(ScriptRuntime.java:393)
2018-02-15 14:28:17 [WARN] 	at jdk.nashorn.api.scripting.NashornScriptEngine.evalImpl(NashornScriptEngine.java:449)
2018-02-15 14:28:17 [WARN] 	... 13 more`

**Comment by lucko** [comment]
Yeah, latest update needs work - just switch back to the older version.

**Comment by JamieSinn** [comment]
Tag me when you've got a working build.

**Comment by andrewkm** [comment]
@lucko any news on this? Ready to test here :)

**Comment by lucko** [comment]
Sorry, I'm super busy atm.

Feel free to have a play around with it yourself, will happily accept a PR which fixes things. :)

**Comment by lucko** [comment]
Fixed in 510b9bb490c574297d927a3b4c75c84fe502cde4

**Comment by JamieSinn** [comment]
Seems like there have been some API changes at least.

`2018-04-02 15:10:43 [WARN] plugins/helper-js/scripts/bin/lobby/gui.js:8 TypeError: gui.bindRunnable is not a function
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.runtime.Undefined.lookup(Undefined.java:102)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:106)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.runtime.linker.NashornLinker.getGuardedInvocation(NashornLinker.java:98)
2018-04-02 15:10:43 [WARN] 	at jdk.internal.dynalink.support.CompositeTypeBasedGuardingDynamicLinker.getGuardedInvocation(CompositeTypeBasedGuardingDynamicLinker.java:176)
2018-04-02 15:10:43 [WARN] 	at jdk.internal.dynalink.support.CompositeGuardingDynamicLinker.getGuardedInvocation(CompositeGuardingDynamicLinker.java:124)
2018-04-02 15:10:43 [WARN] 	at jdk.internal.dynalink.support.LinkerServicesImpl.getGuardedInvocation(LinkerServicesImpl.java:154)
2018-04-02 15:10:43 [WARN] 	at jdk.internal.dynalink.DynamicLinker.relink(DynamicLinker.java:253)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.scripts.Script$Recompilation$726$214$gui.serverSelectGui#redraw(plugins/helper-js/scripts/bin/lobby/gui.js:8)
2018-04-02 15:10:43 [WARN] 	at me.lucko.helper.menu.Gui$$NashornJavaAdapter.redraw(Unknown Source)
2018-04-02 15:10:43 [WARN] 	at me.lucko.helper.menu.Gui.open(Gui.java:255)
2018-04-02 15:10:43 [WARN] 	at me.lucko.helper.menu.Gui$$NashornJavaAdapter.open(Unknown Source)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.scripts.Script$Recompilation$481$1200A$gui.L:41(plugins/helper-js/scripts/bin/lobby/gui.js:42)
2018-04-02 15:10:43 [WARN] 	at me.lucko.helper.command.functional.FunctionalCommandHandler$$NashornJavaAdapter.handle(Unknown Source)
2018-04-02 15:10:43 [WARN] 	at me.lucko.helper.command.functional.FunctionalCommand.call(FunctionalCommand.java:58)
2018-04-02 15:10:43 [WARN] 	at me.lucko.helper.command.AbstractCommand.onCommand(AbstractCommand.java:75)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:648)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1397)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.chat(PlayerConnection.java:1313)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.entity.CraftPlayer.chat(CraftPlayer.java:239)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.internal.scripts.Script$Recompilation$603$862A$events.L:27(plugins/helper-js/scripts/bin/lobby/events.js:31)
2018-04-02 15:10:43 [WARN] 	at jdk.nashorn.javaadapters.java.util.function.Consumer.accept(Unknown Source)
2018-04-02 15:10:43 [WARN] 	at me.lucko.helper.utils.Delegates$ConsumerToBiConsumerSecond.accept(Delegates.java:149)
2018-04-02 15:10:43 [WARN] 	at me.lucko.helper.event.functional.single.HelperEventListener.execute(HelperEventListener.java:134)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.plugin.TimedRegisteredListener.callEvent(TimedRegisteredListener.java:36)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:235)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:202)
2018-04-02 15:10:43 [WARN] 	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:198)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1435)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:24)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.PacketPlayInArmAnimation.a(PacketPlayInArmAnimation.java:1)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13)
2018-04-02 15:10:43 [WARN] 	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
2018-04-02 15:10:43 [WARN] 	at java.util.concurrent.FutureTask.run(Unknown Source)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679)
2018-04-02 15:10:43 [WARN] 	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577)
2018-04-02 15:10:43 [WARN] 	at java.lang.Thread.run(Unknown Source)`

**Comment by lucko** [comment]
Yes, the version was bumped to `5.0.0` to reflect that.
