### ISSUE TITLE
InaccessibleObjectException on startup with Java 16

### ISSUE THREAD

**Issue by Pugabyte** [lucko/helper#98]
```
[11:25:38] [Server thread/INFO]: [helper] Loading helper v5.6.7
[11:25:38] [Server thread/INFO]: [helper] helper (me.lucko.helper) bound to plugin helper - me.lucko.helper.internal.StandalonePlugin
[11:25:38] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_16_R3.CraftServer] null initializing helper v5.6.7 (Is it up to date?)
java.lang.ExceptionInInitializerError: null
        at me.lucko.helper.plugin.ExtendedJavaPlugin.onLoad(ExtendedJavaPlugin.java:78) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.loadPlugins(CraftServer.java:394) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:252) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1065) ~[patched_1.16.5.jar:git-Paper-629]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:289) ~[patched_1.16.5.jar:git-Paper-629]
        at java.lang.Thread.run(Thread.java:831) [?:?]
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make protected void java.net.URLClassLoader.addURL(java.net.URL) accessible: module java.base does not "opens java.net" to unnamed module @6f514ac
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:357) ~[?:?]
        at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
        at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
        at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
        at me.lucko.helper.maven.LibraryLoader.<clinit>(LibraryLoader.java:51) ~[?:?]
        ... 6 more
```

Paper 1.16.5 #654
Java 16 (OpenJDK 64-Bit Server VM 16.0.1+9-Ubuntu-120.04) Host: Linux 5.4.0-29-generic (amd64)

**Comment by Pugabyte** [comment]
@lucko Hi, sorry to bother you, can you explain why this fixes this error? I'm genuinely curious and don't understand

**Comment by lucko** [comment]
The actual dependency loader will still not work on Java 16, however, this change makes it so that plugins not using the loader can still enable.

**Comment by GeorgeV220** [comment]
Hey,
so i'm guessing this cannot be fixed or you need to find another way to load dependencies on runtime..

**Comment by PepejHa4ker** [comment]
Add this argument to command: --add-opens java.base/java.lang=ALL-UNNAMED

**Comment by PepejHa4ker** [comment]
The problem arises from 9 Java, due to a change in semantics of setAccessible method

**Comment by PepejHa4ker** [comment]
@lucko, i think, MethodHandles and your shadow library may fix the issues, https://gist.github.com/PepejHa4ker/dbd32f406c521cd682e00b7e1cd731b3

**Comment by lucko** [comment]
Shadow isn't compatible either unfortunately

**Comment by GeorgeV220** [comment]
Hey,
you can always add ```--add-opens java.base/java.net=ALL-UNNAMED```
for my test server i'm using ```java --add-opens java.base/java.net=ALL-UNNAMED --add-opens java.base/java.lang.invoke=ALL-UNNAMED -Xms128M -Xmx4096M -Dterminal.jline=false -Dterminal.ansi=true -jar purpur.jar```

**Comment by PepejHa4ker** [comment]
@GeorgeV220, the solution has already been provided, see above

**Comment by GeorgeV220** [comment]
@PepejHa4ker, you need ```java.base/java.net``` for that in order to work, ```java.base/java.lang``` will not work in this situation!!
But your answer helped me to find out how to do it so thank you ^-^

**Comment by nagarpankaj** [comment]
Where to add this above parameter. Because while compiling I am getting this error
